### ISSUE TITLE
Highlight Satispay enablement

### ISSUE THREAD

**Issue by verlok** [tomma5o/domicilioBoilerplate#18]
It would be extremely interesting to see whether or not each business accepts SatisPay or other payment methods that doesn’t require exchange of money or payment cards. 

It would be PERFECT if there was a _click to pay_ call to action directly in the businesses list, which one could click and open the SatisPay app, or the PayPal app, etc. with the business view already open

**Comment by tomma5o** [comment]
This is a very great idea 👍

**Comment by verlok** [comment]
I've succesfully added a Satispay small test under each business in imoladomicilio.it

![image](https://user-images.githubusercontent.com/1127721/79670557-3e7a5880-81c4-11ea-876d-ce5ddf0184c9.png)

PR will follow

**Comment by verlok** [comment]
Pulled #45
