### ISSUE TITLE
Make it installable on Android

### ISSUE THREAD

**Issue by verlok** [tomma5o/domicilioBoilerplate#19]
The manifest.json is already there. Just add a simple service worker. 

https://web.dev/codelab-make-installable/

**Comment by tomma5o** [comment]
Probably you have forked an older version ;)
The new one has the sw.js with the route of the `PREACT_APP_DATA_SOURCE` cached ;)

**Comment by verlok** [comment]
I did, and I'll do a PR now to get alignet, but I've checked ferraradomicilio.it on my wife's Huawei phone, and it didn't prompt any "install me" feature...

**Comment by tomma5o** [comment]
I Think PR #22 fix this when I have time I'll merge that

**Comment by tomma5o** [comment]
Hey, @verlok now the PR #22 is live can you check if the problem is solved?

**Comment by verlok** [comment]
Done

**Comment by LorenzoCamporesi** [comment]
@verlok the problem it's not solved?

**Comment by verlok** [comment]
It’s solved now, it’s just that I hadn’t yet.
