### ISSUE TITLE
Add integration with Google Analytics

### ISSUE THREAD

**Issue by verlok** [tomma5o/domicilioBoilerplate#20]
Via something like a new config. 
Google Analytics ID = `ua-123123123-1`
And you're ready to go.

**Comment by tomma5o** [comment]
Here in the [README.md](https://github.com/tomma5o/domicilioBoilerplate/blob/master/README.md) there is a small guide on how to configure GA w/ Netlify ;)

**Comment by verlok** [comment]
Done
