### ISSUE TITLE
Add opening time data to shop

### ISSUE THREAD

**Issue by LorenzoCamporesi** [tomma5o/domicilioBoilerplate#23]
I think that it can be a good idea to add an opening time option that works like the note option.

**Comment by verlok** [comment]
I'm currently writing both the opening times and the payment methods in the note field and I don't think it's a best practice.

Anyway, given that opening times can change frequently, I'm not sure this is a good idea, unless we integrate it with a CMS 😅

I'm proposing an alternative solution on #24

**Comment by tomma5o** [comment]
Thanks for the PR @LorenzoCamporesi !
I think the icons are becoming a few too many, we need a sort of ℹ️ icon that displays all the info of the store: site, mail, opening hours ecc ecc.

I don't know if a drop-down is still a good idea 🤔

What do you think?

**Comment by LorenzoCamporesi** [comment]
Yes, I think that can be a very good idea to put info snippet, to solve the snippet problem and keep it we can:
- in the same line as the shop's name
   - phone number
   - note
   - info icon
- in the info snippet 
  - the first line:
    - website icon
    - google maps link (#24) with an icon
    - email icon
  - the next lines
   - opening time

**Comment by tomma5o** [comment]
We can integrate into the second line the enhancement #18 .

For the opening times, I don't know if is a good choice take this ownership 🤔 
Do we really want to update the opening hours every time?
I think leave the problem to google is a good choice.

**Comment by verlok** [comment]
Me too. Also because we currently don’t have any “edit” button (only the “add” one) and to create an edit button would be tricky. And hard to maintain on our side.

**Comment by LorenzoCamporesi** [comment]
> For the opening times, I don't know if is a good choice take this ownership

We can simply add it and people that use the boilerplate choose if use it or not.

> I think leave the problem to google is a good choice.

It is a good idea for smart people, but in my small city a lot of shops hadn't updated it and probably will never do it.
I will add this feature in my forked version, it's not a problem if you will not add that here in the main boilerplate.

> We can integrate into the second line the enhancement #18 .

Yes, and maybe, if we choose to have it, we can move the opening time in a popup.
