### ISSUE TITLE
Add link to place in Google Maps

### ISSUE THREAD

**Issue by verlok** [tomma5o/domicilioBoilerplate#24]
What about introducing a link to the place on Google Maps so that:

- we don't have to update the opening times in our information (would solve #23)
- users can read reviews about the places, and eventually place the phone call from there

What do you think?
cc @LorenzoCamporesi

**Comment by LorenzoCamporesi** [comment]
I think that it's a very good idea. 
I'm not sure that solve the problem of the opening time because I've seen that in this period shop changed it and I don't know if all updated it on maps.

**Comment by verlok** [comment]
Yes you’re right but it’s probably more updated on Google Maps then on our app

**Comment by verlok** [comment]
I changed my mind, I think that a link to the Facebook page of the businesses is more than enough.
