### ISSUE TITLE
Add Facebook page to data

### ISSUE THREAD

**Issue by verlok** [tomma5o/domicilioBoilerplate#32]
Some people have reported both the website and the Facebook page, I’ve tried inserting it as an array in the web field but it doesn’t work. 

It’s probably a good idea to add the Facebook page link to the information, given that most people have them updated more than the real website.

**Comment by tomma5o** [comment]
I think this is related to #29
We need a sort of detail page were we show all the info, or for this, we can use the same dialog used for the multiple phone number

**Comment by verlok** [comment]
I solved this on imoladomicilio.it, I can PR if you like

**Comment by verlok** [comment]
Pull requested #44
