### ISSUE TITLE
Math.random in index.js

### ISSUE THREAD

**Issue by verlok** [tomma5o/domicilioBoilerplate#36]
I think you left a Math.random in index.js by mistake. 
This generates many cache entries in SW cache and never uses it.

![image](https://user-images.githubusercontent.com/1127721/79032171-aa493980-7ba4-11ea-848b-38bd04761ab6.png)

**Comment by tomma5o** [comment]
Is a temporary workaround because i think the gist route don’t have a way for understand when a new version is available.

If the memory available for the sw is full workbox purge the old one 👍🏻

**Comment by verlok** [comment]
I got it, I'm just warning you because now the service worker is useless. I mean: it caches everything else but note the data. So if you go offline or on a slow connection, the app won't get any data, so it would be useless.

**Comment by tomma5o** [comment]
Ok, I've understood the problem, I've wrongly renamed the method of the personal plugin for the `StaleWhileRevalidate` class ;)
