### ISSUE TITLE
Add the number of total existing shops

### ISSUE THREAD

**Issue by ciu8** [tomma5o/domicilioBoilerplate#39]
Just see the number of the shops existing
![image](https://user-images.githubusercontent.com/12743236/79556618-a1270380-80a1-11ea-83e8-85948db295fb.png)

**Comment by verlok** [comment]
Having number of activities and their categories would be even better. Something like:

**"A {città} ci sono le seguenti {number} tra {categoria 1}, {categoria 2}, {categoria 3} che consegnano a domicilio"**

In plain language:

**"A Ferrara sono presenti 145 tra Ristoranti, Pizzerie, Paninoteche, Chioschi, etc. che consegnano a domicilio".**

This would be very positive for SEO.

Sadly, my currently low knowledge of React doesn't allow me to do it myself. But I'll try harder in the future.

**Comment by ciu8** [comment]
> Having number of activities and their categories would be even better. Something like:
> 
> **"A {città} ci sono le seguenti {number} tra {categoria 1}, {categoria 2}, {categoria 3} che consegnano a domicilio"**
> 
> In plain language:
> 
> **"A Ferrara sono presenti 145 tra Ristoranti, Pizzerie, Paninoteche, Chioschi, etc. che consegnano a domicilio".**
> 
> I think this would be very positive for SEO.
> 
> Sadly, my currently low knowledge of React doesn't allow me to do it myself. But I'll try harder in the future.

good idea but i'd prefer to have a general sentence at the moment because don't need to know which categories are present and don't need to transform into plural.
I don't like to have static categories that may not be present.

**Comment by verlok** [comment]
> don't need to know which categories are present
> I don't like to have static categories that may not be present.

You already have the categories in the JSON data file, you are in control

> and don't need to transform into plural.

You wouldn't need to change anything into plural, the category names are already plural.

> I'll change into "A Ferrara sono presenti 145 attività che consegnano a domicilio"

That wouldn't be a really useful information for the final users, and it wouldn't have any positive effect on SEO. 

That said, you can do only that if you want, and we can build from there.

**Comment by ciu8** [comment]
Yes, i totally agree with you. Sorry, probably i was a little bit tired when i wrote that!

I have all the information i need so i can do what you suggested; probably i'll limit to 3 the number of the shops in the subtitle to prevent a looong sentence.

Regards!

**Comment by ciu8** [comment]
an Example:
![image](https://user-images.githubusercontent.com/12743236/80003847-e5f7d380-84c1-11ea-9243-a7b46690088f.png)

**Comment by verlok** [comment]
That's exactly what I meant, @ciu8 !
Have you release that already on your fork?

**Comment by verlok** [comment]
Thanks. Added to [imoladomicilio](https://imoladomicilio.it) too!
